### ISSUE TITLE
Unable to instantiate subclassed optimizer (bug with `swappable_by_subclassing`)

### ISSUE THREAD

**Issue by rsomani95** [MrThearMan/graphene-django-query-optimizer#117]
### I have read the docs thoroughly before making this bug report.

- [X] Yes

### I have read through other open issues, and my issue is not a duplicate.

- [X] Yes

### What version of the library you are using?

0.8.3

### Which python version are you using?

3.12

### What operating system are you on?

Mac

### Description

Hi again :)

I was trying out the latest version of the optimizer. The subclassing mechanism is really cool in theory, but I ran into an issues when trying to use it in practice. I was able to replicate the error by inserting the following test inside `test_utils.py`:

```python
def test_swappable_optimizer():
    from query_optimizer.optimizer import QueryOptimizer
    from query_optimizer.typing import TModel

    class CustomOptimizer(QueryOptimizer):
        def optimize_queryset(self):
            return None

    # PS: I know the init args aren't correct, but they are still technically valid... they also fail when
    # passing in an actual model and queryset but I've simplified it for reproducibility here)
    x = CustomOptimizer(None, None)
    assert type(x) is CustomOptimizer
    assert x.optimize_queryset() is None
```

When running the test, I am encountered with this error, which stems from trying to instantiate `CustomOptimizer()`:
```bash
======================================================== FAILURES ========================================================
________________________________________________ test_swappable_optimizer ________________________________________________

    def test_swappable_optimizer():
        from query_optimizer.optimizer import QueryOptimizer
        from query_optimizer.typing import TModel
    
        class CustomOptimizer(QueryOptimizer):
            def optimize_queryset(self):
                return None
    
>       x = CustomOptimizer(None, None)

test_utils.py:194: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

_ = <class 'tests.test_utils.test_swappable_optimizer.<locals>.CustomOptimizer'>, args = (None, None), kwargs = {}

    def new(_: type, *args: Any, **kwargs: Any) -> Ttype:
>       return super(type, new_subcls).__new__(new_subcls, *args, **kwargs)
E       TypeError: object.__new__() takes exactly one argument (the type to instantiate)

../query_optimizer/utils.py:206: TypeError

```

**Comment by rsomani95** [comment]
Perhaps relevant: https://stackoverflow.com/questions/59217884/new-method-giving-error-object-new-takes-exactly-one-argument-the-typ

I'm having a hard time wrapping my head around python's subclassing and `__new__`.

This modification I tried feels wrong (as we're simply omitting passing down the `*args` and `**kwargs` but it's unclear to me how `__new__` uses it) but lets me initialise the custom class successfully. Thought it might be worth sharing:

```python
def swappable_by_subclassing(obj: Ttype) -> Ttype:
    """Makes the decorated class return the most recently created direct subclass when it is instantiated."""
    orig_init_subclass = obj.__init_subclass__

    def init_subclass(*args: Any, **kwargs: Any) -> None:
        nonlocal obj

        new_subcls: type = obj.__subclasses__()[-1]

        def new(_: type, *args: Any, **kwargs: Any) -> Ttype:
            # return super(type, new_subcls).__new__(new_subcls, *args, **kwargs)
            return super(type, new_subcls).__new__(new_subcls)

        obj.__new__ = new

        return orig_init_subclass(*args, **kwargs)

    obj.__init_subclass__ = init_subclass
    return obj
```

**Comment by MrThearMan** [comment]
The issue seems to be in passing arguments to the constructor of a swapped class. Indeed, this [seems to be explained in the StackOverflow thread you posted](https://stackoverflow.com/a/65862579) - just one of python's many quirks! Not passing the args to `__new__` should be the solution. Released this in [v0.8.4](https://github.com/MrThearMan/graphene-django-query-optimizer/releases/tag/v0.8.4).

Ps. While you _can_ initialize the subclass, the point of `swappable_by_subclassing` is that the parent class will initialize as the subclass. 

```python
class CustomOptimizer(QueryOptimizer):
    def optimize_queryset(self):
        return None

x = QueryOptimizer(None, None)

assert type(x) == CustomOptimizer
```

This way I don't need to write any additional code to replace the use of the class in the library code, and you don't need to pass the class anywhere. Just making sure the subclass is created created is enough.

**Comment by rsomani95** [comment]
@MrThearMan thanks.
Gotcha re. the init, I was doing that just for the test (though now I realise how I was doing that wrong too haha).

> Just making sure the subclass is created created is enough.

I found that in addition to this, I needed to _import_ the subclass in an 'active' module (even though it's not being instantiated anywhere) for Python to register it. This was probably because I'd defined the optimizer subclass in a module that wasn't being hit by any code path otherwise, but an important detail worth sharing nonetheless.

**Comment by MrThearMan** [comment]
> I needed to import the subclass in an 'active' module (even though it's not being instantiated anywhere) for Python to register it.

This is what I meant. The _class_ will be created when the code is run, i.e. when you import the module containing it. If the code is never run, the class is never created. You _don't_ need to create an _instance_ of the class at any point.
