### ISSUE TITLE
Faster cache retrival for large datasets

### ISSUE THREAD

**Issue by MrThearMan** [MrThearMan/graphene-django-query-optimizer#86]
### Description

When dealing with large datasets (>50 000 rows), its aparrent that the current mechanism for fetching cached data is not very performant. See [this flamegraph](https://github.com/MrThearMan/graphene-django-query-optimizer/assets/17141277/88ff6dd4-a0c8-4b81-b53f-60b4d2fc85a9) (pictured below) for a query for 200 000 rows, where each row has a single child through a foreign key. The actual database query takes ~10% of the request time, while fetcing data from cache is ~60%. In this 60%, constructing the `queryset.filter()` alone is ~30%, while the compiler takes another ~15%, and the actual fetching from the cache is only ~10%.

The current mechanism for caching needs to run the compiler in order to create a unique cache key for a given model row based on the field selections in the GraphQL query, since the it's possible that the same row _could_ appear in the same request with different field selections, and therefore we can't simply use its primary key as the cache keys.

One option could be to have some sort of cache merging stategy, where rows with the same primary keys would be merged to the cache, and then we could simply use the primary keys. How this would work with prefetched and related fields is a mystery though.

Or maybe there is some strategy for storing multiple rows for the same primary key in a way that wouldn't need to know so much about the query? Or maybe there is a way to rely on the order things are inserted to the cache?

This is a longer terms issue, but if you are reading this, suggestions are welcome!

![profile-flame](https://github.com/MrThearMan/graphene-django-query-optimizer/assets/17141277/37076e50-f1f4-4175-a1e3-d7b9c6aac859)

### Motivation

When fetching larger datasets without pagination, fetching from the query can become a bottleneck. Looking at the measurements, this could be made ~2x faster by faster cache retrieval.

**Comment by MrThearMan** [comment]
After looking at this a little bit closer, I noticed that the _entire_ caching mechanism is redudnant, and was there just for one case with related to-one fields. I was able to remove the mechanism, which of course removes this issues. [Here](https://github.com/MrThearMan/graphene-django-query-optimizer/assets/17141277/0c9099a6-88e7-49ff-b874-eadd7874bede) is a link to the after-flamegraph (pictured below).

![profile](https://github.com/MrThearMan/graphene-django-query-optimizer/assets/17141277/0c9099a6-88e7-49ff-b874-eadd7874bede)

Released on [0.5.0](https://github.com/MrThearMan/graphene-django-query-optimizer/releases/tag/v0.5.0).

**Comment by vade** [comment]
BTW Thanks for all your work on the optimizer! This project is awesome :)
